### ISSUE TITLE
Docker Swarm ingress ports

### ISSUE THREAD

**Issue by arun-gupta** [aws-samples/aws-compute-options#10]
The `docker-compose.yaml` has statically assigned ingress ports as:

```
version: '3'
services:
  greeting-service:
    image: arungupta/greeting:latest
    ports:
      - 8081:8080
  name-service:
    image: arungupta/name:latest
    ports:
      - 8082:8080
  webapp-service:
    image: arungupta/webapp:latest
    ports:
      - 80:8080
```

How to make sure that ingress ports are dynamically assigned?
